name: OpenAI Review for Digifly (DGF)

on:
  pull_request:
    types: [closed]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  review:
    # Kør ved merged PR, ved push til main, eller manuelt
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
      OPENAI_THREAD_ID: ${{ secrets.OPENAI_THREAD_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Meta: PR data (tomt ved push) ---
      - name: Collect PR metadata (if PR)
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT
            printf "pr_title<<EOF\n%s\nEOF\n" "${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
            printf "pr_body<<EOF\n%s\nEOF\n" "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
            echo "pr_head_sha=${{ github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            echo "pr_base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "pr_head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "pr_title=" >> $GITHUB_OUTPUT
            echo "pr_body=" >> $GITHUB_OUTPUT
            echo "pr_head_sha=" >> $GITHUB_OUTPUT
            echo "pr_base_sha=" >> $GITHUB_OUTPUT
            echo "pr_head_ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      # --- Vælg base/head afhængigt af event ---
      - name: Determine base and head SHAs
        id: shas
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ steps.meta.outputs.pr_base_sha }}"
            HEAD="${{ steps.meta.outputs.pr_head_sha }}"
          else
            BASE="${{ github.event.before }}"
            HEAD="${{ github.sha }}"
            # Første commit kan have before=0000…
            if [ -z "$BASE" ] || echo "$BASE" | grep -q '^0\{40\}$'; then
              BASE="$(git rev-parse "$HEAD~1" 2>/dev/null || true)"
            fi
          fi
          echo "base=$BASE" >> $GITHUB_OUTPUT
          echo "head=$HEAD" >> $GITHUB_OUTPUT
          echo "Event: ${{ github.event_name }} | BASE=$BASE | HEAD=$HEAD"

      # --- Find DGF-ID ---
      - name: Detect DGF task ID
        id: task
        run: |
          COMBINED="${{ steps.meta.outputs.pr_title }} ${{ steps.meta.outputs.pr_body }} ${{ steps.meta.outputs.pr_head_ref }}"
          TASK_ID="$(printf '%s' "$COMBINED" | grep -oE 'DGF-[0-9]+' | head -n1 || true)"
          echo "task_id=$TASK_ID" >> $GITHUB_OUTPUT
          echo "Detected task: ${TASK_ID:-<none>}"

      # --- Find kravspec (valgfrit) ---
      - name: Locate DGF spec file (optional)
        id: spec
        run: |
          ID="${{ steps.task.outputs.task_id }}"
          FOUND=""
          if [ -n "$ID" ]; then
            for p in \
              "docs/specs/$ID.md" \
              "docs/specs/dgf/$ID.md" \
              ".github/tasks/$ID.md" \
              "specs/$ID.md" \
              "requirements/$ID.md"
            do
              if [ -f "$p" ]; then FOUND="$p"; break; fi
            done
          fi
          echo "spec_path=$FOUND" >> $GITHUB_OUTPUT
          if [ -n "$FOUND" ]; then echo "Using spec: $FOUND"; else echo "No spec file found (optional)."; fi

      # --- Diff ---
      - name: Build diff
        run: |
          BASE="${{ steps.shas.outputs.base }}"
          HEAD="${{ steps.shas.outputs.head }}"
          if [ -n "$BASE" ]; then
            git diff --unified=0 "$BASE" "$HEAD" > code_diff.txt || true
          else
            echo "No previous commit; showing HEAD stats" > code_diff.txt
            git show --stat "$HEAD" >> code_diff.txt || true
          fi
          head -c 12000 code_diff.txt > code_diff_trunc.txt && mv code_diff_trunc.txt code_diff.txt
          echo -e "\n\n[Truncated if large]" >> code_diff.txt

      - name: Install jq
        run: |
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y jq >/dev/null 2>&1 || true

      # --- Prompt (PR + spec + diff) ---
      - name: Build prompt (context + spec + diff)
        run: |
          PR_NUM="${{ steps.meta.outputs.pr_number }}"
          PR_TITLE="${{ steps.meta.outputs.pr_title }}"
          PR_BODY="${{ steps.meta.outputs.pr_body }}"
          TASK_ID="${{ steps.task.outputs.task_id }}"
          SPEC_PATH="${{ steps.spec.outputs.spec_path }}"
          {
            echo "DGF task context"
            echo "-----------------"
            if [ -n "$PR_NUM" ]; then
              echo "PR #$PR_NUM — ${PR_TITLE}"
              echo
              echo "PR description:"
              echo "${PR_BODY}"
            else
              echo "Direct push to branch: ${{ github.ref_name }}"
              echo "Title/Body not available (no PR)."
            fi
            echo
            echo "Detected task ID: ${TASK_ID:-<none>}"
            echo
            if [ -n "$SPEC_PATH" ]; then
              echo "Task spec ($SPEC_PATH):"
              echo '```markdown'
              sed -e 's/\r$//' "$SPEC_PATH"
              echo '```'
              echo
            fi
            echo "Diff"
            echo "----"
            echo '```diff'
            cat code_diff.txt
            echo '```'
            echo
            echo "Please review the implementation **against the DGF task context/spec above** and return:"
            echo "1) Acceptance criteria met? (cite spec/PR lines/sections)"
            echo "2) Risks & bugs/smells"
            echo "3) Breaking changes/migrations"
            echo "4) 3 concrete fixes (with file/line hints)"
            echo "Reply as concise markdown."
          } > prompt.txt

      - name: Build JSON payload
        run: |
          jq -n --rawfile prompt prompt.txt \
            '{
               model: "gpt-4o",
               messages: [
                 {role:"system","content":"You are a senior reviewer for Digifly (DGF). Be precise, pragmatic, brief."},
                 {role:"user","content": $prompt}
               ]
             }' > payload.json

      - name: Ask ChatGPT for feedback
        id: openai
        run: |
          set -e
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY is missing"; exit 1
          fi
          RESPONSE=$(curl -sS https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            --data @payload.json)
          echo "$RESPONSE" > response.json
          jq -r '.choices[0].message.content // "No content returned"' response.json > feedback.txt
          echo "------- ChatGPT feedback (preview) -------"
          head -n 100 feedback.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dgf-review
          path: |
            prompt.txt
            payload.json
            response.json
            code_diff.txt
            feedback.txt

      # --- Teams posting med DGF-overskrift ---
      - name: Post to Microsoft Teams
        if: ${{ success() && env.TEAMS_WEBHOOK_URL != '' }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          TASK_ID="${{ steps.task.outputs.task_id }}"
          PR_TITLE="${{ steps.meta.outputs.pr_title }}"
          if [ -z "$TASK_ID" ]; then
            TITLE="ChatGPT DGF review: (no task id) — ${PR_TITLE:-Direct push}"
          else
            TITLE="ChatGPT DGF review: ${TASK_ID} — ${PR_TITLE:-Direct push}"
          fi
          head -c 6000 feedback.txt > feedback_trunc.txt
          jq -n \
            --arg title "$TITLE" \
            --arg run_url "$RUN_URL" \
            --arg feedback "$(cat feedback_trunc.txt)" \
            '{
              "@type":"MessageCard",
              "@context":"https://schema.org/extensions",
              "summary":"DGF review",
              "themeColor":"7A4ED9",
              "title": $title,
              "sections":[{"text": $feedback}],
              "potentialAction":[{"@type":"OpenUri","name":"View workflow run","targets":[{"os":"default","uri": $run_url}]}]
            }' > teams.json
          curl -sS -H "Content-Type: application/json" -d @teams.json "$TEAMS_WEBHOOK_URL" || true

      # --- (Valgfrit) log til Assistants tråd (ingen polling, bare log) ---
      - name: Log to Assistants thread
        if: ${{ success() && env.OPENAI_THREAD_ID != '' && env.OPENAI_ASSISTANT_ID != '' }}
        run: |
          # Log prompt
          CONTENT="$(cat prompt.txt | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')"
          echo "{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"[DGF] Review context used:\\n\\n$CONTENT\"}]}" > thread_msg.json
          curl -sS -X POST "https://api.openai.com/v1/threads/${OPENAI_THREAD_ID}/messages" \
            -H "Authorization: Bearer ${OPENAI_API_KEY}" \
            -H "Content-Type: application/json" \
            --data @thread_msg.json >/dev/null 2>&1 || true
          # Log feedback
          FB="$(cat feedback.txt | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')"
          echo "{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"[Assistant feedback posted to Teams]:\\n\\n$FB\"}]}" > thread_fb.json
          curl -sS -X POST "https://api.openai.com/v1/threads/${OPENAI_THREAD_ID}/messages" \
            -H "Authorization: Bearer ${OPENAI_API_KEY}" \
            -H "Content-Type: application/json" \
            --data @thread_fb.json >/dev/null 2>&1 || true

      - name: Clean up
        if: always()
        run: |
          rm -f prompt.txt payload.json response.json code_diff.txt feedback.txt feedback_trunc.txt teams.json thread_msg.json thread_fb.json || true
